### PR TITLE
Update

### PR DESCRIPTION
**Pull request by NataliiaHue**
I've revised the sources.csv file and updated the spread sheets respectively in the "raw" folder.

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
Looks good. I'll adapt the CLDF creation script to work from this raw data now. The files in `cldf_like_files` can then be deleted, right?

**Comment by NataliiaHue** [comment]
Thanks!!
And yes, most of`cldf_like_files` can be deleted. I would like to preserve the file with the examples though, because I cleaned them up manually a bit, is it possible?

**Comment by xrotwang** [comment]
Yes, we can keep the examples, I'll move them to `etc/examples.csv` then. Does this mean you are not adding examples to the raw sheets anymore?

**Comment by xrotwang** [comment]
Here's the author-year-refs in the raw sheets that I couldn't match to `etc/sources.csv`:
```
('Pakendorf', 'in preparation') 55
('Janhunen', '2010') 7
('Kuular', '2007') 3
('Pakendorf', '430-445') 2
('Ramstedt', '1935') 1
('Krueger', '1962') 1
('Achundova', '1971') 1
('Shimunek', '2001') 1
('Lie', '1978') 1
('Sakhmayev', '1994') 1
('Poppe', '1951') 1
('Weiers', '1975') 1
('Anonymous', '1954') 1
```
All the singletons may be typos, I guess. Could you fix these?

**Comment by NataliiaHue** [comment]
Thank you! I'll have a look at them and let you know.

**Comment by NataliiaHue** [comment]
And I won't be adding examples to raw sheets. Moreover, once the article is out, I shouldn't be changing anything in this data set, right?

**Comment by xrotwang** [comment]
Not necesarily. That's the nice thing about versioning and Zenodo: You can release a version of the dataset which the paper is based on, and then an extended version next year, for the next paper. Or release v0.1 which paper submission is based on, and then possibly a corrected version v1.0 upon acceptance of the paper.

**Comment by xrotwang** [comment]
The set after merging this PR is:
```
('Janhunen', '2003') 208
('Pakendorf', 'in preparation') 55
('Janhunen', '2010') 7
('Kuular', '2007') 3
('Yakup', 'in press') 2
('Pakendorf', '430-445') 2
('Ramstedt', '1935') 1
('Krueger', '1962') 1
('Oskolskaya', 'p.c.') 1
('Achundova', '1971') 1
('Shimunek', '2001') 1
('Lie', '1978') 1
('Sakhmayev', '1994') 1
('Poppe', '1951') 1
('Robbeets', '2017') 1
('Weiers', '1975') 1
('Anonymous', '1954') 1
```

**Comment by NataliiaHue** [comment]
Some of the references are no longer in the raw data because the features were deleted (e.g. Anonymous 1954 was for feature TE044, which is no longer there). Should I go on checking these references or do you have an updated list, after the feature deletion?

**Comment by xrotwang** [comment]
I don't have an updated list, but the cldf creation works such that only sources that are actually referenced from `cldf/values.csv` are written to `cldf/sources.bib`. The updated list of refs I couldn't match is:
```
('Janhunen', '2003') 162
('Pakendorf', 'in preparation') 53
('Janhunen', '2010') 7
('Yakup', 'in press') 2
('Pakendorf', '430-445') 2
('Oskolskaya', 'p.c.') 1
('Robbeets', '2017') 1
```

**Comment by NataliiaHue** [comment]
Thank you! It's gotten shorter! Now I indeed find them in the raw data. What do I do if I need to change the reference: do I change it in raw data or in values.csv or in both? Is it ok that I edited the references in the raw data for the previous revision?

**Comment by xrotwang** [comment]
Never change things in any of the files in `cldf/`. All of these are generated. Editing in the raw data is ok.

**Comment by NataliiaHue** [comment]
Thank you! I realise that it was a mistake to edit the examples manually in an extra file, but I didn't know better at that point and I didn't know whom I can discuss my problems with (the examples were terribly misaligned because of multiple rows in one cell and I couldn't easily bring them in order in the raw tsv data). Now I have a better version of the examples in the extra file and an old version in the raw data, but that's how it is now...

**Comment by xrotwang** [comment]
I think it wasn't a bad idea to move the examples to a separate file, in particular because you sometimes have more than one example for one value. The one in `etc/examples.csv` is the one to edit.

**Comment by NataliiaHue** [comment]
that's right! Multiple examples per value were a huge problem and I didn't know, which layout to use for collecting my data, but it's nice to hear you don't find it a horrible idea. I've been editing `etc/examples.csv` until now.

**Comment by xrotwang** [comment]
The general `cldfbench` idea is that
- `raw/` has the data in its original form
- `etc/` adds data which does not come from the original source, but is added by the curators of the dataset (if they are distinct from the collectors)
- `cldf/` contains the CLDF data synthesized from the other two directories automatically.

So in your case, we could also keep `examples.csv` in `raw/`. But I'm happy with things as they are organized now, too.

**Pull request merged**
